### ISSUE TITLE
Change csrutil recommendation to confine allowance to kext signing

### ISSUE THREAD

**Issue by arubdesu** [jzdziarski/flockflock#1]
While this is temporary until your kext is signed, and even though allowing kexts with any signature (or none at all) is still Not A Good Thing™ in the meantime, it's too often SIP gets treated like 'turn off all the things!' when instead you can disable and then run `csrutil enable --without kext`. (As described [here](https://derflounder.wordpress.com/2015/10/01/system-integrity-protection-adding-another-layer-to-apples-security-model/) under "Other custom SIP configuration options".)

**Comment by jzdziarski** [comment]
Great tip, thanks! I've updated the README.
