### ISSUE TITLE
postinstall script should use quotes around paths.

### ISSUE THREAD

**Issue by vivami** [jzdziarski/flockflock#3]
The `postinstall` script shouldn't use the quotes around the paths. It's causing the installer to fail creating the LaunchAgent directory. Manually checked below:

![](https://cl.ly/gsO4/Screen%20Shot%202016-08-04%20at%2010.42.14%20AM.png)

**Comment by vivami** [comment]
This is apparently not the cause, since `postinstall` is using `/bin/sh`, for which quotes work. However, upon installing FF_0.0.8, the `~/Library/LaunchAgents` directory is not created.

**Comment by jzdziarski** [comment]
Good catch, thanks. Removing the quotes did fix it in the pkg.
