### ISSUE TITLE
Remarks regarding FlockFlock

### ISSUE THREAD

**Issue by pwnsdx** [jzdziarski/flockflock#4]
Hello,

Thanks you for creating FlockFlock, it's an ingenious and well-made piece of software. I really hope it will go far.

I discovered that FlockFlock user's file can be reset in a really easy way so I was wondering will FlockFlock Persistence module will prevent a malware from doing the same thing please? https://twitter.com/pwnsdx/status/761660939812868096

Also, I wanted to warn you that Arq 5 backup ("arqcommiter" process) completely bypass FlockFlock. I use it to backups some folders on my network and while the backup was working I got no alert from your software. My arqcommiter run as unprivilegied user (but it can be run as root as well by checking the option "Back up using administrator privileges" available in the preferences).

By the way you blocked me on Twitter (@pwnsdx), I don't know why but I guess it was for a really good reason :)

Regards,
Sabri

**Comment by jzdziarski** [comment]
Persistence prevents modification of flockflockrc files. But deleting one doesn't do anything but cause FlockFlock to ask the user again about files they've whitelisted or blacklisted. The default rules live in /Library/Application Support/FlockFlock. Persistence prevents those from being deleted too although you'd have to be root to delete them anyway. 

The only software that is capable of bypassing FF is anything running as a kernel module. If you've installed a kernel module then I'm assuming you trust it.

**Comment by pwnsdx** [comment]
> Persistence prevents modification of flockflockrc files. But deleting one doesn't do anything but cause FlockFlock to ask the user again about files they've whitelisted or blacklisted. The default rules live in /Library/Application Support/FlockFlock. Persistence prevents those from being deleted too although you'd have to be root to delete them anyway.

Good then! Sure it's not a security issue but if a malware could delete the user's .flockflockrc file the user will assume it was a FlockFlock bug and will have to whitelist/blacklist everything again, as there is a lot of popups on the first launch, he could allow something that was denied in the old .flockflockrc.

Or worst, the malware could delete the .flockflockrc everytime it's created so at each reboot FlockFlock will ask everything again, this will likely going to annoy the user which will probably uninstall FlockFlock and grant the malware full permissions.

> The only software that is capable of bypassing FF is anything running as a kernel module. If you've installed a kernel module then I'm assuming you trust it.

Here's the thing: Arq have no kernel module(s).

Cheers,

**Comment by jzdziarski** [comment]
I'd look at where you have it installed and consider removing it from the default policy list then. We whitelist /System, /usr/sbin and a few other trusted locations by default. Would need a lot more detail to give you an exact explanation but I'd start there.

**Comment by pwnsdx** [comment]
arqcommiter is run under my session "sabri" and is in `/Applications/Arq.app/Contents/Library/LoginItems/Arq Agent.app/Contents/Resources` and the targeted folders for backup are in `/Users/sabri/Desktop/*`

Little Snitch identify arqcommiter as arqcommiter but it seems that your software identify arqcommiter as Arq Agent.app (`/Applications/Arq.app/ via Arq Agent`)

But as you can see the rules does permit Arq Agent.app to read files in `/Users/sabri/Desktop/*` so that's strange.

**Comment by jzdziarski** [comment]
Try removing the white listed folders from the master rules list, then reboot. May also help to delete your rc file just to be safe. It may be talking to a component in System or somewhere else. Deleting all the white lists should at least tell you what it's talking to. Make sure you're using alpha 0.0.12 so we're on the same page.

**Comment by jzdziarski** [comment]
Ah you know what I think I have some old debug code left in there to ignore processes that already exist like daemons to avoid giving me problems. I'll remove that code and commit a build tonight. That could very well be it if this is a daemon.

**Comment by pwnsdx** [comment]
I use the 0.0.12. I've deleted .flockflockrc file and rebooted, I got all popups regarding Arq and no one regarding the "YOU SHALL NOT PASS.txt" file, it has been uploaded now, weird.

**Comment by pwnsdx** [comment]
Oh, I hope the issue come from here then :)

**Comment by pwnsdx** [comment]
Just tried the 0.0.13 and arqcommitter is now detected :)

![screen shot 2016-08-06 at 04 08 11](https://cloud.githubusercontent.com/assets/2057765/17454145/7afdf65c-5b8c-11e6-965a-6744c4c50517.png)

However, new popup spawned like revisiond, screencapture, mds... so there is much more popups.

![screen shot 2016-08-06 at 04 08 27](https://cloud.githubusercontent.com/assets/2057765/17454153/a3748164-5b8c-11e6-9485-5610c3144e02.png)

**Comment by jzdziarski** [comment]
awesome, I will clean up the code then and commit .14 shortly to confirm it’s still fixed.
