### ISSUE TITLE
SlowSlow

### ISSUE THREAD

**Issue by Zevran** [jzdziarski/flockflock#5]
Hi,

Your tool is awesome, check everything and customization rules are right the way !
But when FlockFlock is activated, it increase the speed to access to a file, I know it's completely normal but are there other possibilities to check rules in .flockflockrc rather than through a file ?

I am not a security expert so please don't blame me if I write something stupid.

Could it be possible to store rules in a binary tree (may be AVL to reduce tree size) or in a radix tree ? And pre-compile it or something like that ? 

Otherwise keep going, your tool is great :)

**Comment by jzdziarski** [comment]
Everything is stored in memory, not read from the file; if you can provide some performance stats about everything going on on your machine, as well as kernel task, that would be helpful, always working on optimizing performance, but do not presently see what you're experiencing. If you provide more information, feel free to re-open the issue. Thanks.

**Comment by jzdziarski** [comment]
also please have a go at the latest alpha, as some performance improvements were made around build 27
