### ISSUE TITLE
Include conservative default ruleset

### ISSUE THREAD

**Issue by tomtastic** [jzdziarski/flockflock#7]
To prevent some frustration for new users (several minutes of consecutive rule popups), could we see a default conservative ruleset included?

I'm thinking of the default MacOS apps like grab, preview, quickview, etc. being allowed access to their savedstate directories / all .tiff|.jpg files as appropriate.

**Comment by jzdziarski** [comment]
build 41 now has a default option to allow apps access to their own containers, caches, and saved application state (for signed apps installed in /Applications); this should cut back on the noise considerably without having to add a set of rules (note: this can be turned off in the default .flockflockrc)
